[versions]
agp = "9.0.0"
kotlin = "2.3.0"
ksp = "2.3.4"

core-ktx = "1.17.0"
appcompat = "1.7.1"
activity = "1.12.2"
viewbinding = "9.0.0"
constraintlayout = "2.2.1"
activity-ktx = "1.12.2"
fragment-ktx = "1.8.9"
multidex = "2.0.1"
window = "1.5.1"

coroutines = "1.10.2"
lifecycle-extensions = "2.2.0"
lifecycle = "2.10.0"
material-icons-core = "1.7.8"
material-icons-extended = "1.7.8"
material = "1.13.0"
hilt = "2.59"
datastore = "1.2.0"
room = "2.8.4"
navigation = "2.9.6"
paging = "3.3.6"

retrofit = "3.0.0"
okhttp = "5.3.2"
cookie = "v1.0.1"

junit = "4.13.2"
androidx-junit = "1.3.0"
espresso-core = "3.7.0"

tinypinyin = "2.0.3"
glide = "5.0.5"

[libraries]

#base
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-viewbinding = { group = "androidx.databinding", name = "viewbinding", version.ref = "viewbinding" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity-ktx" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment-ktx" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "window" }

#kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

#coroutines
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

#lifecycle
lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle-extensions" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycle" }

#material
material-icons-core = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "material-icons-core" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material-icons-extended" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

#hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }

#datastore
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

#room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-rxjava2 = { group = "androidx.room", name = "room-rxjava2", version.ref = "room" }
room-guava = { group = "androidx.room", name = "room-guava", version.ref = "room" }

#navigation
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

#paging
paging = { group = "androidx.paging", name = "paging-common", version.ref = "paging" }

#retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
persistent-cookie-lar = { group = "com.github.franmontiel", name = "PersistentCookieJar", version.ref = "cookie" }

#junit
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

#pinyin
tinypinyin = { group = "com.github.promeg", name = "tinypinyin", version.ref = "tinypinyin" }

#glide
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

#compiler
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
